// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bulkybookweb.Data;

#nullable disable

namespace bulkybookweb.Migrations
{
    [DbContext(typeof(Applicationdbcontext))]
    [Migration("20230429134144_SeedCategoryTable")]
    partial class SeedCategoryTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("bulkybookweb.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrdr")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CreatedDateTime = new DateTime(2023, 4, 29, 19, 26, 44, 8, DateTimeKind.Local).AddTicks(4635),
                            DisplayOrdr = 1,
                            Name = "Action"
                        },
                        new
                        {
                            id = 2,
                            CreatedDateTime = new DateTime(2023, 4, 29, 19, 26, 44, 8, DateTimeKind.Local).AddTicks(4647),
                            DisplayOrdr = 2,
                            Name = "Scifi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
